version: "3.8"


services:
  mongo:
  
    image: mongo

    ports:
    - 27017:27017

    environment:

      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
      
    # you can change according to your pc path
    volumes:
      - /home/krish/Desktop/data:/data/db
    

  mongo-express:

      image: mongo-express

      ports:
      - 8081:8081

      environment:

        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
        ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/
        ME_CONFIG_BASICAUTH_USERNAME: admin
        ME_CONFIG_BASICAUTH_PASSWORD: qwerty

      


  testapp:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: testapp
      ports:
        - 5050:5050
      depends_on:
        - mongo
      

